import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

// Body parsing with size limits for screenshot uploads
app.use(express.json({ limit: "50mb" }));
app.use(express.urlencoded({ limit: "50mb", extended: true }));

// Lazy initializer for Google Gen AI client
let aiInstance: GoogleGenAI | null = null;
function getGenAI(): GoogleGenAI {
  if (!aiInstance) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      console.warn("WARNING: GEMINI_API_KEY environment variable is not set. AI functions will fail or use fallback systems.");
    }
    aiInstance = new GoogleGenAI({
      apiKey: apiKey || "MOCK_KEY",
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiInstance;
}

// Ensure database updates are saved in mock local database or state.
// We'll create robust standard endpoints for tracking students' metrics.
interface PracticeAttempt {
  id: string;
  subject: string;
  score: number;
  totalQuestions: number;
  timestamp: string;
}

interface SavedNote {
  id: string;
  title: string;
  content: string;
  subject: string;
  timestamp: string;
}

// In-Memory Database for student persistence (with server persistence as requested)
const studentDatabase = {
  attempts: [
    { id: "1", subject: "Science (Physics)", score: 8, totalQuestions: 10, timestamp: "2026-05-28T10:00:00Z" },
    { id: "2", subject: "Mathematics", score: 9, totalQuestions: 10, timestamp: "2026-05-28T14:30:00Z" },
    { id: "3", subject: "History", score: 5, totalQuestions: 5, timestamp: "2026-05-29T09:12:00Z" },
  ] as PracticeAttempt[],
  notes: [
    {
      id: "note-1",
      title: "Newton's Laws of Motion",
      subject: "Science (Physics)",
      content: "### Newton's Laws Summary\n\n1. **First Law (Inertia)**: An object remains at rest or in uniform motion unless acted upon by an external force.\n2. **Second Law (F = ma)**: Force is equal to mass times acceleration.\n3. **Third Law (Action & Reaction)**: For every action, there is an equal and opposite reaction.\n\n*Important formula:* $F = m \\times a$",
      timestamp: "2026-05-28T10:15:00Z"
    },
    {
      id: "note-2",
      title: "Quadratic Equation Roots",
      subject: "Mathematics",
      content: "### Roots of $ax^2 + bx + c = 0$\n\n- Discriminant: $D = b^2 - 4ac$\n- Real roots if $D \\ge 0$\n- Complex roots if $D < 0$\n\nFormula:\n$$x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}$$",
      timestamp: "2026-05-28T14:45:00Z"
    }
  ] as SavedNote[],
  timerStreak: 4, // days
  focusTimeTotal: 125, // minutes
  predictedScore: 92, // percent
};

// --- API ROUTES ---

// Health check
app.get("/api/health", (req, res) => {
  res.json({ status: "ok", time: new Date().toISOString() });
});

// Student metrics fetch
app.get("/api/student/dashboard", (req, res) => {
  res.json(studentDatabase);
});

// Save practice test score
app.post("/api/student/practice", (req, res) => {
  const { subject, score, totalQuestions } = req.body;
  if (!subject || score === undefined || !totalQuestions) {
    res.status(400).json({ error: "Missing required fields" });
    return;
  }
  const newAttempt: PracticeAttempt = {
    id: String(Date.now()),
    subject,
    score: Number(score),
    totalQuestions: Number(totalQuestions),
    timestamp: new Date().toISOString(),
  };
  studentDatabase.attempts.push(newAttempt);

  // Recalculate predicted score based on last active attempts
  const totalCorrect = studentDatabase.attempts.reduce((acc, sub) => acc + sub.score, 0);
  const totalAsked = studentDatabase.attempts.reduce((acc, sub) => acc + sub.totalQuestions, 0);
  if (totalAsked > 0) {
    studentDatabase.predictedScore = Math.round((totalCorrect / totalAsked) * 100);
  }

  res.json({ success: true, updatedAttempts: studentDatabase.attempts, predictedScore: studentDatabase.predictedScore });
});

// Save notes generated by AI
app.post("/api/student/notes", (req, res) => {
  const { title, content, subject } = req.body;
  if (!title || !content || !subject) {
    res.status(400).json({ error: "Missing required fields" });
    return;
  }
  const newNote: SavedNote = {
    id: "note-" + Date.now(),
    title,
    content,
    subject,
    timestamp: new Date().toISOString()
  };
  studentDatabase.notes.unshift(newNote);
  res.json({ success: true, note: newNote, allNotes: studentDatabase.notes });
});

// Delete saved note
app.delete("/api/student/notes/:id", (req, res) => {
  const { id } = req.params;
  const index = studentDatabase.notes.findIndex(n => n.id === id);
  if (index !== -1) {
    studentDatabase.notes.splice(index, 1);
    res.json({ success: true, allNotes: studentDatabase.notes });
  } else {
    res.status(404).json({ error: "Note not found" });
  }
});

// Study activity logger (focus time, streaks)
app.post("/api/student/track-timer", (req, res) => {
  const { durationMinutes } = req.body;
  if (!durationMinutes || isNaN(durationMinutes)) {
    res.status(400).json({ error: "Invalid duration" });
    return;
  }
  studentDatabase.focusTimeTotal += Number(durationMinutes);
  // Increment streak if it was tracked today
  studentDatabase.timerStreak = Math.min(30, studentDatabase.timerStreak + 1);
  res.json({ success: true, totalFocusMinutes: studentDatabase.focusTimeTotal, timerStreak: studentDatabase.timerStreak });
});

// 🤖 AI Tutor Multimodal Chat
app.post("/api/gemini/chat", async (req, res) => {
  try {
    const { message, history, imageBase64, mimeType } = req.body;
    if (!message && !imageBase64) {
      res.status(400).json({ error: "Empty request. Send message or image." });
      return;
    }

    const ai = getGenAI();

    // Prepare system instruction for the perfect, ultimate personal AI Tutor:
    const systemInstruction = 
      "You are MRIVAN AI - a world-class premium personal AI teacher and expert academic coach for students. " +
      "Your tone is inspiring, encouraging, highly smart, professional, yet simple and friendly. " +
      "Always break down complex concepts into simple steps with real-life analogies. " +
      "You support teaching all school and university subjects from Physics and Calculus to Business and History. " +
      "If the user asks questions or provides files and speaks/asks in Hindi, Bhojpuri, Hinglish or English, reply in that exact preferred language/mix code with superb eloquence. " +
      "Make learning fun. Highlight important formulas, provide quick study tips, and ask one engaging follow-up question at the end to keep the student curious. " +
      "Use LaTeX / Markdown formatting where helpful.";

    // Handle multimodal upload or pure text chat
    const contents: any[] = [];

    // Append chat history in the format that the API likes or format manually
    // For standard contents send, we can formulate our prompt with context:
    let formattedPrompt = "";
    if (history && history.length > 0) {
      formattedPrompt += "CHAT HISTORY CONTEXT:\n";
      history.forEach((h: any) => {
        const roleName = h.role === "user" ? "Student" : "MRIVAN AI Tutor";
        formattedPrompt += `${roleName}: ${h.content}\n`;
      });
      formattedPrompt += `\nNEW STUDENT QUESTION: ${message}`;
    } else {
      formattedPrompt = message || "Explain this image";
    }

    // Prepare parts
    const parts: any[] = [];
    if (imageBase64 && mimeType) {
      parts.push({
        inlineData: {
          mimeType: mimeType,
          data: imageBase64
        }
      });
    }
    parts.push({ text: formattedPrompt });

    // Call generateContent with model gemini-3.5-flash
    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: { parts },
      config: {
        systemInstruction,
        temperature: 0.7,
      }
    });

    res.json({ text: response.text });
  } catch (error: any) {
    console.error("Error in AI Tutor Chat API:", error);
    res.status(500).json({ error: error.message || "An error occurred with MRIVAN AI." });
  }
});

// 🤖 AI study notes generation
app.post("/api/gemini/notes", async (req, res) => {
  try {
    const { topic, subject, language } = req.body;
    if (!topic || !subject) {
      res.status(400).json({ error: "Missing topic or subject" });
      return;
    }

    const ai = getGenAI();
    const systemInstruction = 
      "You are a premium curriculum notes developer for MRIVAN AI. " +
      "Your task is to generate comprehensive, highly structured, clear revision and study notes. " +
      "Provide headings, bold highlight, numbered formulas, key vocabulary lists, and a 'Summary & Speed Revision' section. " +
      "Structure the notes eloquently using beautiful Markdown and LaTeX. " +
      "Include realistic examples and tips to score highest in exams. " +
      "Write predominantly in the requested language: " + (language || "English") + ".";

    const prompt = `Generate expert revision notes for Chapter/Topic: "${topic}" in the subject of "${subject}". Include definitions, key formulas, examples, and 3 high-yield questions for self-assessments.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        systemInstruction,
        temperature: 0.6,
      }
    });

    res.json({ notes: response.text });
  } catch (error: any) {
    console.error("Error in AI Notes Generator API:", error);
    res.status(500).json({ error: error.message || "An error occurred during notes generation." });
  }
});

// 🤖 AI exam generator (returns structured JSON questions)
app.post("/api/gemini/quiz", async (req, res) => {
  try {
    const { subject, topic, level, numQuestions } = req.body;
    if (!subject) {
      res.status(400).json({ error: "Subject is required" });
      return;
    }

    const ai = getGenAI();
    const count = numQuestions || 5;
    const requestedTopic = topic || "General Concepts";
    
    const prompt = `Create a high-quality assessment quiz of exactly ${count} Multiple Choice Questions (MCQs) for the subject "${subject}" specifically on the topic "${requestedTopic}". The difficulty level should be "${level || "Medium"}". Provide accurate, logical options.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        systemInstruction: "You are a professional examiners board officer generating clean academic test questions. Each question must have exactly 4 logical options and a clear explanation detailing why the correctAnswer is correct.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            questions: {
              type: Type.ARRAY,
              description: `List of exactly ${count} multiple choice questions.`,
              items: {
                type: Type.OBJECT,
                properties: {
                  question: { type: Type.STRING },
                  options: {
                    type: Type.ARRAY,
                    items: { type: Type.STRING },
                    description: "Exactly 4 options."
                  },
                  correctAnswer: { 
                    type: Type.STRING, 
                    description: "The exact correct option string. Must match one of the items inside 'options' array exactly." 
                  },
                  explanation: { type: Type.STRING, description: "Detailed educational reasoning behind the correct option." }
                },
                required: ["question", "options", "correctAnswer", "explanation"]
              }
            }
          },
          required: ["questions"]
        }
      }
    });

    const parsedJson = JSON.parse(response.text || "{}");
    res.json(parsedJson);
  } catch (error: any) {
    console.error("Error in AI Exam Generator API:", error);
    res.status(500).json({ error: error.message || "An error occurred during quiz generation." });
  }
});


// Serve React Frontend (Vite Setup)
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`MRIVAN AI full-stack server running on http://localhost:${PORT}`);
  });
}

startServer();
